name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 5.1.1
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

publish_to: none

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  intl: ^0.18.1
  template_string:
    git:
      url: https://github.com/FernandoDev007/flutter_sheet_localization.git
      path: template_string
