name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

publish_to: none

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^0.13.1
  meta: ^1.3.0
  csv: ^6.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0 
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^4.7.0
  collection: ^1.15.0
  intl: ^0.18.1
  flutter_sheet_localization:
    git:
      url: https://github.com/FernandoDev007/flutter_sheet_localization.git
      path: flutter_sheet_localization
  template_string:
    git:
      url: https://github.com/FernandoDev007/flutter_sheet_localization.git
      path: template_string
  localization_builder:
    git:
      url: https://github.com/FernandoDev007/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.0.2
