name: example
publish_to: none

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter 
  logging: ^1.0.0
  http: ^0.13.0
  csv: ^5.0.0
  template_string:
    git:
      url: https://github.com/FernandoDev007/flutter_sheet_localization.git
      path: template_string
  localization_builder:
    git:
      url: https://github.com/FernandoDev007/flutter_sheet_localization.git
      path: localization_builder